### ISSUE TITLE
coinfest 2025

### ISSUE THREAD

**Issue by Kandanurarafah** [Kandanurarafah/would-be-come-coinfest-2025#1]
Coinfest Asia is Asia largest crypto and Web3 festival, bringing together industry leaders, innovators and communities to discuss, learn and collaborate on developing the future of Web3 technology. Held annually in , Coinfest Asia continues to be a premier platform for the industry crypto.the festival indeed invites many investors in Asia, including shareholders, which will be the beginning of the progress of the crypro industry. With the ease of communication, there will be a time when in Asia, Indonesia will be the biggest adopter.. Yes, I think that why because Indonesia occupies the position Top with the popularity of Asians who are enough to socialize with each other, we'll see haha 
 ( warning also this picture are copyright of someone else !! )
![coinfest2024](https://github.com/user-attachments/assets/a60c3155-31e5-4ff2-9845-e020aafa405e)

**Comment by Kandanurarafah** [comment]
> Coinfest Asia is Asia largest crypto and Web3 festival, bringing together industry leaders, innovators and communities to discuss, learn and collaborate on developing the future of Web3 technology. Held annually in , Coinfest Asia continues to be a premier platform for the industry crypto.the festival indeed invites many investors in Asia, including shareholders, which will be the beginning of the progress of the crypro industry. With the ease of communication, there will be a time when in Asia, Indonesia will be the biggest adopter.. Yes, I think that why because Indonesia occupies the position Top with the popularity of Asians who are enough to socialize with each other, we'll see haha ( warning also this picture are copyright of someone else !! ) ![coinfest2024](https://private-user-images.githubusercontent.com/181180988/383759485-a60c3155-31e5-4ff2-9845-e020aafa405e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MzY3ODUsIm5iZiI6MTczMDkzNjQ4NSwicGF0aCI6Ii8xODExODA5ODgvMzgzNzU5NDg1LWE2MGMzMTU1LTMxZTUtNGZmMi05ODQ1LWUwMjBhYWZhNDA1ZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNlQyMzQxMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzA4N2U2MTNlYjYyZDkxNGVmOTNlZTgzMzE4MDRmYzk3ZDA5OTk3MmMyYTRhNTBmZTlmZWU0MjUyMzE3MDk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.E4_hVjpQzG_wewzXjzZJhkx_6PqCaTnIT2_22z27XCk)

**Comment by etherian3** [comment]
Adalah muhuns
